---
# database parameters
databaseType: sqlite3 # this field is required
databaseConnStr: ../../data/seekret.db # this field is required

# http server parameters
httpServerPort: 3553 # defaults to 3553 if not provided
